# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Yes_button(object):
    def setupUi(self, Yes_button):
        Yes_button.setObjectName("Yes_button")
        Yes_button.resize(576, 237)
        self.input_label = QtWidgets.QLabel(Yes_button)
        self.input_label.setGeometry(QtCore.QRect(30, 10, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_label.setFont(font)
        self.input_label.setObjectName("input_label")
        self.input_edit = QtWidgets.QLineEdit(Yes_button)
        self.input_edit.setGeometry(QtCore.QRect(30, 60, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.input_edit.setFont(font)
        self.input_edit.setObjectName("input_edit")
        self.input_label_2 = QtWidgets.QLabel(Yes_button)
        self.input_label_2.setGeometry(QtCore.QRect(30, 100, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_label_2.setFont(font)
        self.input_label_2.setObjectName("input_label_2")
        self.select_button = QtWidgets.QPushButton(Yes_button)
        self.select_button.setGeometry(QtCore.QRect(30, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_button.setFont(font)
        self.select_button.setObjectName("select_button")
        self.yes_button = QtWidgets.QPushButton(Yes_button)
        self.yes_button.setGeometry(QtCore.QRect(340, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.yes_button.setFont(font)
        self.yes_button.setObjectName("yes_button")

        self.retranslateUi(Yes_button)
        QtCore.QMetaObject.connectSlotsByName(Yes_button)

    def retranslateUi(self, Yes_button):
        _translate = QtCore.QCoreApplication.translate
        Yes_button.setWindowTitle(_translate("Yes_button", "Form"))
        self.input_label.setText(_translate("Yes_button", "请输入:"))
        self.input_label_2.setText(_translate("Yes_button", "或者进行路径选择:"))
        self.select_button.setText(_translate("Yes_button", "选择"))
        self.yes_button.setText(_translate("Yes_button", "确定"))
