# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(580, 331)
        self.top_label = QtWidgets.QLabel(Form)
        self.top_label.setGeometry(QtCore.QRect(190, 0, 291, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        self.top_label.setFont(font)
        self.top_label.setObjectName("top_label")
        self.bind_game_button = QtWidgets.QPushButton(Form)
        self.bind_game_button.setGeometry(QtCore.QRect(20, 40, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.bind_game_button.setFont(font)
        self.bind_game_button.setObjectName("bind_game_button")
        self.set_resolution_button = QtWidgets.QPushButton(Form)
        self.set_resolution_button.setGeometry(QtCore.QRect(200, 40, 201, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.set_resolution_button.setFont(font)
        self.set_resolution_button.setObjectName("set_resolution_button")
        self.test_button = QtWidgets.QPushButton(Form)
        self.test_button.setGeometry(QtCore.QRect(410, 40, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.test_button.setFont(font)
        self.test_button.setObjectName("test_button")
        self.settings_button = QtWidgets.QPushButton(Form)
        self.settings_button.setGeometry(QtCore.QRect(230, 100, 141, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.settings_button.setFont(font)
        self.settings_button.setObjectName("settings_button")
        self.copyright_button = QtWidgets.QLabel(Form)
        self.copyright_button.setGeometry(QtCore.QRect(0, 230, 541, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.copyright_button.setFont(font)
        self.copyright_button.setObjectName("copyright_button")
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setGeometry(QtCore.QRect(160, 170, 291, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.version_label = QtWidgets.QLabel(Form)
        self.version_label.setGeometry(QtCore.QRect(30, 290, 261, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(13)
        self.version_label.setFont(font)
        self.version_label.setObjectName("version_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.top_label.setText(_translate("Form", "   简单性能优化"))
        self.bind_game_button.setText(_translate("Form", "绑定游戏路径"))
        self.set_resolution_button.setText(_translate("Form", "设置指定分辨率"))
        self.test_button.setText(_translate("Form", "可行性测试"))
        self.settings_button.setText(_translate("Form", "配置菜单"))
        self.copyright_button.setText(_translate("Form", "    软件来源:bilibili-w_风月无情,本身免费,无毒"))
        self.start_button.setText(_translate("Form", "开始监听并启动游戏"))
        self.version_label.setText(_translate("Form", "版本:1.0"))
